[server]
# 服务器配置
addr = "127.0.0.1:9999"

[[output]]
name = "测试codesign 安卓"
description = "测试codesign功能是否正常"
base_path = "test"
format = ["v1","v2","v3"]
# 压缩包的格式,这里的文件必须跟format对应
zip_format = ["mipmap-mdpi/","mipmap-hdpi/","mipmap-xhdpi/"]
format_limit = [".png",".svg"]

[[output]]
name = "测试codesign WEB"
description = "测试codesign功能是否正常"
base_path = "test"
format = ["web-v1","web-v2"]
# 压缩包的格式,这里的文件必须跟format对应
zip_format = ["./**.png","./**@2x.png"]
format_limit = [".png",".svg"]

[[output]]
name = "测试codesign IOS"
description = "测试codesign功能是否正常"
base_path = "test"
format = ["ios-v1","ios-v2","ios-v3"]
# 压缩包的格式,这里的文件必须跟format对应
zip_format = ["./**.png","./**@2x.png","./**@3x.png"]
format_limit = [".png",".svg"]


