[server]
# 服务器配置
addr = "127.0.0.1:9999"
# 后续补充日志相关配置

## 这里的配置，如果新增的话，一定要按照顺序往下新增，不要插叙乱序修改，历史记录用到了这里的索引,后续可能考虑使用key来区分
[[output]]
name = "输出目录的名字，例如：安卓，IOS，flutter"
description = "输出目录描述"
base_path = "文件路径，例如：./ui,注：./ui 跟 ./ui/ 是等价的"
# 多倍图格式,例如： name.png v2/name.png v3/name.png对应的目录为：. v2/ v3/
# 注意：这里的格式必须跟压缩包真实的格式一致
format = [".","v2/","v3/"]
# 压缩包的格式,这里的文件必须跟format对应
zip_format = ["1.png","2.png","3.png"]
# 切图的格式限制，例如：.png,.svg
format_limit = [".png",".svg"]

[[output]]
name = "输出目录的名字，例如：安卓，IOS，flutter"
description = "输出目录描述"
base_path = "文件路径，例如：./ui,注：./ui 跟 ./ui/ 是等价的"
# 多倍图格式,例如： name.png v2/name.png v3/name.png对应的目录为：. v2/ v3/
# 注意：这里的格式必须跟压缩包真实的格式一致,这里的format是相对base_path的路径
format = ["1","2","3"]
# 压缩包的格式,这里的文件必须跟format对应
zip_format = ["1.png","2.png","3.png"]
# 切图的格式限制，例如：.png,.svg
format_limit = [".png",".svg"]
